### ISSUE TITLE
Seal of Command extra delay

### ISSUE THREAD

**Issue by sofuckingawesome** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3240]
Hello,

This report is on the Seal of Command proc extra delay which was added recently so the paladins could sealtwist finally. However, the delay is supposed to be 0.5s, but the actual delay is like 3s.

The following info is about how it's supposed to work.

http://www.wowwiki.com/Seal_of_Command_(old)

Patch 1.11.0 (20-Jun-2006):
Since Patch 1.11, Seal of Command proc will have approximately 0.5 second delay before the animation begins and the Holy damage is incurred, instead of having the proc occur instantly with the swing of the attack.

The following info is how it works right now.

http://youtu.be/dqzOXle46Bg

I hope you'll get this fixed soon.

Thank you.

**Comment by Involve** [comment]
***Current Situation:***
The spell Seal of Command (ID: 27170) has a roughly 3 second delay after proccing from a swing.
***Desired Situation:***
Instead, Seal of Command should, as OP already stated, have about half a second of delay before the ANIMATION happens and the HOLY DAMAGE is applied.

***Reproduction Guide:***

You will need two clients in order to reproduce this issue:

Client A:
Any class/race
.gm off
.gm visible on
.levelup 69
.t test
.aura 1908

Client B
Create a Paladin
.gm off
.gm visible on
.levelup 69
.t test
.learn 202
.learn 27170
.add 34247

http://i.imgur.com/JNAohNG.jpg
http://i.imgur.com/oK4MQ5m.png

Start a duel with any Client and cast Seal of Command on Client B. Start autohitting Client A until Seal of Command procs. Notice the time inbetween the swing that procced the ability, and the actual damage done of Seal of Command. Having a Combatlog display with timestamps enabled helps enormously.
Furthermore, note that currently, the animation for Seal of Command occurs as soon it procs (aka with the autohit) however, it should instead proc when Seal of Command actually does damage (aka 0.5s after it procs)

**Comment by Tudi** [comment]
Rejected. Could not reproduce. On my local test server there is 0 delay. Combat log IS affected by latency = live server combat log timestamp difference is normal.

Please note that the images in the above report do not show the same seal of command proc. Client A deals 2112 damage and client B receives 1921 / 2018 damage.

**Comment by roblockster** [comment]
The images aren't supposed to show timestamps, I believe. Instead they show that the Seal of Casino proc from white hits are hitting about 3 seconds later.

**Comment by mondegoftw** [comment]
The delay is real. Please check again. It's around 3 seconds on the live server, and this is a huge blow for ret palas, (especially non-horde ones, which are weak already). Also makes for some seriously nasty seal twisting burst capabiltiies for horde rets, which are nowhere near blizzlike. This along with the CS proccing SoB bug lets horde paladins deal the damage from a SoC proc, melee + SoB, CS + SoB all in less than 0.5 seconds. Seriously needs fixing.

Please look into this. I'd show proof with more screenshots, but they would look identical to those posted by Involve.

**Comment by mondegoftw** [comment]
Is anyone looking at this? A 3 second delay on the perhaps most basic ret paladin spell is completely gamechanging for alliance paladins (who don't benefit from having SoB, which also is bugged, but in a way that makes horde palas overpowered).

Should be easy to confirm (as per Involve's https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3240#issuecomment-98537381 from May) and fix.

**Comment by kamil87** [comment]
I just started a Paladin I wonder how i'll be able to PVP with a 3 sec delay on SoC I just noticed it while killing monster, at least I can twist with SoR hehe.

**Comment by devidao** [comment]
Fixed, coming soon on PTR

**Comment by Nzzoth** [comment]
Fix denied on PTR.

**Comment by soda09** [comment]
There is still a 3 sec delay

**Comment by AcidScytheZ** [comment]
Hello  guys :) I've started to play here before few days and noticed this bug from the beginning....
I was like oh i can report it on forums and then i saw that the bug has been reported before 2 years..............
How is still not fixed?
This makes me to not play here ehm................
SoC delay still exist, it does damage like 3-5 sec after the proc which is kinda gamebreaking for pvp.
