### ISSUE TITLE
Righteous Weapon Coating

### ISSUE THREAD

**Issue by kildrazien** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3760]
Item Righeous Weapon Coating is currently not working. When equipped to a weapon in isle of quel'danas you never see any procs. This is a huge thing for some classes, especially hunters, in sunwell plateau if it does not work. 

To reproduce:

Place a rogue in Isle of Quel'Danas
Equip a weapon
Apply Righteous Weapon coating (https://www.wow-one.com/database/index.php?item=34539) to weapon
Create a warrior with 1000000 health
Swing against the warrior with the rogue
notice how you never gain the appropriate buff Righteousness (https://www.wow-one.com/database/index.php?spell=45401)

**Comment by devidao** [comment]
Fixed. Coming soon on PTR.
- buffs from 'Righteous Weapon Coating' and 'Blessed Weapon Coating' enchantments are gained with 15 % chance and have 45 seconds cooldown
- they can be gained only on Isle of Quel'Danas, on the Magisters' Terrace, and on the Sunwell Plateau

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by Nzzoth** [comment]
Fix confirmed on PLTR.

**Comment by Applescruffs** [comment]
Confirmed working for melee attacks on live realm.

However, it is not proccing off of ranged attacks.

**Comment by meowmewo** [comment]
Hello? Are hunters getting the Ignore again? Like they did with Steady Shot for 3 years? This is STILL not working for ranged attacks. Sunwell is here now, this should have been fixed. Why is it fixed for melee attacks but not ranged.

**Comment by ghost** [comment]
Any news regarding ranged proc issues?

**Comment by meowmewo** [comment]
Bump, start getting serious.

**Comment by meowmewo** [comment]
Still not working for hunters.
