### ISSUE TITLE
Windfury totem chainprocs.

### ISSUE THREAD

**Issue by Cerebov** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3777]
cant belive nobody reported this yet. this has been going on for almost a month.
Tested on archangel. windfury _totem_ procs off itself resulting in 2,3,4,5 additional autoswings instead of just 1. 
nothing too special in pve, but in pvp it results in massive spikes capable of one-shotting peopl. crucial.

_Same thing with Lightning overload(elem shaman talent). Procs off itself resulting in additional dmg. 
^Need confirmation on Overload._ **NVM THIS ONE**

edit 
https://www.youtube.com/watch?v=HHmV1a_8FAo

**Comment by Nzzoth** [comment]
Hello Cerebov, thank you for the report. Could you please provide some evidence to back up your claims before I go test and confirm the issue. Thanks in advance.

**Comment by Urshark** [comment]
Hi, 

I didnt see this problem in BGs as ele shaman. Lightning overload worked properly as it should I didn´t see any problewm with it, maybe video could be more helpfull. Same with WF totem in BGs. 
But I don´t play arenas, maybe is the situation not the same in arenas.

**Comment by Dorakrab** [comment]
i can confirm this issue, and i am also surprised that noone haven't said anything in a month. Going to upload some screenshots after today's raid

**Comment by Urshark** [comment]
Hm, it looks that windfury totem realy doesnt work as it should. So this is realy frustrating. Windfury weapon spell doesn´t work properly - enha shamans make realy low dmg so playing enha is imposible, but windfury totem is a big advantage for other melees...

**Comment by Dorakrab** [comment]
yes that is the case right now, here's the video : 

https://www.youtube.com/watch?v=HHmV1a_8FAo

**Comment by Cerebov** [comment]
It seems that lightning overload doesnt chainproc, althou it procs weirdly on 4+ targets, cant say if its a bug or not.
False alert.

**Comment by corcaroli** [comment]
@Cerebov:
I haven't really tested this on my shaman, but to me it appears that every of three Chain Lightning hits(jumps) of the initial spell can proc Lightning Overload on the according target. 
That means that if only one hit out of those three triggers it, we get one additional CL, which makes 6 total hits. If two hits trigger LO, we get two additional CLs => 9 total hits. And finally, if we're lucky and every CL jump triggers LO, we get three additional CLs and thus 12 total hits.
I'm assuming this since i haven't ever noticed LO chain-trigger while casting my lightning spells on a single target for two years.

**Comment by repae1f** [comment]
perfect pvp on feenix 
http://i.imgur.com/gpPojET.png 

so sad

**Comment by Dorakrab** [comment]
quote from latest community update : "as we have limited dev power, try to explain how important the issue is! no bumping!"

So that's what im trying to do. This is one of the most severe issues that has ever happened on Archangel, it results in melees having ridiculous dps increase in raids, and some crazy ass shit in arenas, and this issue did not even get assigned a tag yet, which leads me to believe that noone is looking into it. 

P.S. its been going on since late January/early February

**Comment by Dorakrab** [comment]
"I would usher you to please refresh your topic within the bug tracker so that our development team may do some further testing and work out any issues affecting this spell"

**Comment by repae1f** [comment]
http://www.wow-one.com/forum/topic/105928-community-update/?page=2#comment-767027

**Comment by Zerixx** [comment]
The problem isn't that it procs off itself.. it procs off of yellow hits of any kind.. Which is incorrect. Looking into it asap.

**Comment by Cerebov** [comment]
No, the problem is that windfury totem proc procs off other windfury totem proc.
I just tested mortal strike, hamstring, crusader strike, seal of command and its judgement, seal of blood. None of that triggers windfury.

But if you just put totem and autoattack doing nothing else - that can lead to 3+ swings off 1 autoattack.

**Comment by Cerebov** [comment]
Also, Id like to clarify that this is windfury _totem_, not _weapon_.
It has nothing to do with wf imbue that shamans use for themselves only.
Something tells me that if i dont clarify this, something could go very very wrong.

**Comment by devidao** [comment]
Fixed

**Comment by Qingle** [comment]
This still has not been pushed onto live, can we please get an update as to whether this ever will be pushed.

Qingle

**Comment by endemol88** [comment]
bump

**Comment by ghost** [comment]
@Qingle @endemol88 we'll look at organizing something this coming week if possible to finalize testing and perform an update. Lot of attention on SWP at the moment.

**Comment by lajhar** [comment]
Fix denied on PTR.
Windfury totem still procs off on Windfury attack, therefore resulting not +1, but +2 (0,2x0,2 chance) or +3 (0,2x0,2x0,2 chance) attack. It doesn't proc off on yellow hits anymore, but the issue still reamins.

**Comment by repae1f** [comment]
any news?(
